on:
  repository_dispatch:
    types: [run_deploy]
name: Run Deploy
jobs:
  test:
    name: Run your tests
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "I just ran all your tests!"
          
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER_NAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "./*"
          target: ${{ secrets.REMOTE_TARGET}}
